package push_apps_manager 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type DatabasesAppUsageService struct {

	/*Ip - Descr: IP of database server for the app usage service Default: <nil>
*/
	Ip interface{} `yaml:"ip,omitempty"`

	/*Password - Descr: Password credential for the app usage service Default: <nil>
*/
	Password interface{} `yaml:"password,omitempty"`

	/*Name - Descr: Database name for the app usage service Default: <nil>
*/
	Name interface{} `yaml:"name,omitempty"`

	/*Port - Descr: Port of database server for the app usage service Default: <nil>
*/
	Port interface{} `yaml:"port,omitempty"`

	/*Username - Descr: Username credential for the app usage service Default: <nil>
*/
	Username interface{} `yaml:"username,omitempty"`

	/*Adapter - Descr: Adapter type (mysql2 or postgresql) for the app usage service database Default: mysql2
*/
	Adapter interface{} `yaml:"adapter,omitempty"`

}