package push_apps_manager 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type Env struct {

	/*AppsManagerConfigJson - Descr: White labeling for navigation links Default: [map[name:Marketplace href:/marketplace] map[name:Docs href:http://docs.run.pivotal.io] map[name:Tools href:/tools]]
*/
	AppsManagerConfigJson *AppsManagerConfigJson `yaml:"apps_manager_config_json,omitempty"`

	/*SystemOrgQuotaName - Descr: The name of the quota to be assigned to the system org Default: runaway
*/
	SystemOrgQuotaName interface{} `yaml:"system_org_quota_name,omitempty"`

	/*CfLoggregatorHttpUrl - Descr: Full URL of Loggregator's HTTP API Default: <nil>
*/
	CfLoggregatorHttpUrl interface{} `yaml:"cf_loggregator_http_url,omitempty"`

	/*UsageServiceHost - Descr: The host for the usage service Default: <nil>
*/
	UsageServiceHost interface{} `yaml:"usage_service_host,omitempty"`

	/*CfCcApiUrl - Descr: Full URL of Cloud Foundry API Default: <nil>
*/
	CfCcApiUrl interface{} `yaml:"cf_cc_api_url,omitempty"`

	/*CfNotificationsServiceUrl - Descr: Full URL of Notifications Service's HTTP API Default: <nil>
*/
	CfNotificationsServiceUrl interface{} `yaml:"cf_notifications_service_url,omitempty"`

	/*GenericWhiteLabelConfigJson - Descr: Global Wrapper Footer Content Default: 
*/
	GenericWhiteLabelConfigJson *GenericWhiteLabelConfigJson `yaml:"generic_white_label_config_json,omitempty"`

	/*SecretToken - Descr: Secret token for signing cookies Default: <nil>
*/
	SecretToken interface{} `yaml:"secret_token,omitempty"`

	/*InvitationsClientSecret - Descr: Client secret for the invitations service Default: 
*/
	InvitationsClientSecret interface{} `yaml:"invitations_client_secret,omitempty"`

	/*CfLoggregatorWebsocketUrl - Descr: Full URL of Loggregator's WebSocket endpoint Default: <nil>
*/
	CfLoggregatorWebsocketUrl interface{} `yaml:"cf_loggregator_websocket_url,omitempty"`

}