package push_apps_manager 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type PushAppsManagerJob struct {

	/*Services - Descr: Cloud Foundry UAA server URL Default: <nil>
*/
	Services *Services `yaml:"services,omitempty"`

	/*Ssl - Descr: When displaying external app route urls, prefix all of them with https Default: false
*/
	Ssl *Ssl `yaml:"ssl,omitempty"`

	/*AppUsageService - Descr: How recent is too recent to trust an event Default: 60
*/
	AppUsageService *AppUsageService `yaml:"app_usage_service,omitempty"`

	/*Env - Descr: Display Marketplace Service Plan Prices Default: false
*/
	Env *Env `yaml:"env,omitempty"`

	/*Databases - Descr: Database name for the app usage service Default: <nil>
*/
	Databases *Databases `yaml:"databases,omitempty"`

	/*Cf - Descr: Cloud Foundry apps domain, used for default app domains Default: <nil>
*/
	Cf *Cf `yaml:"cf,omitempty"`

}