package push_apps_manager 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type PushAppsManagerJob struct {

	/*Cf - Descr: Cloud Foundry apps domain, used for default app domains Default: <nil>
*/
	Cf *Cf `yaml:"cf,omitempty"`

	/*Env - Descr: Global Wrapper Footer Content Default: 
*/
	Env *Env `yaml:"env,omitempty"`

	/*AppUsageService - Descr: Whether or not to allow manual creation of AppEvents Default: false
*/
	AppUsageService *AppUsageService `yaml:"app_usage_service,omitempty"`

	/*Databases - Descr: Port of database server for the app usage service Default: <nil>
*/
	Databases *Databases `yaml:"databases,omitempty"`

	/*Ssl - Descr: When displaying external app route urls, prefix all of them with https Default: false
*/
	Ssl *Ssl `yaml:"ssl,omitempty"`

	/*Services - Descr: UAA client secret for Console application Default: <nil>
*/
	Services *Services `yaml:"services,omitempty"`

}