package push_apps_manager 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type Services struct {

	/*Authentication - Descr: Cloud Foundry UAA server URL Default: <nil>
*/
	Authentication *Authentication `yaml:"authentication,omitempty"`

}